### ISSUE TITLE
filter in pipeline doesn't work

### ISSUE THREAD

**Issue by alexanderkogan** [dvallin/spacegun#67]
**Describe the bug**
When using filter on planClusterDeployment spacegun doesn't filter the plan. It won't work with neither ClusterDeployment nor ImageDeployment

**To Reproduce**
1. add "filter' to a pipeline in the plan step
2. run `spacegun run -p plan`

**Expected behavior**
Only the defined namespace or deployment are planned.

**Desktop (please complete the following information):**
 - OS: arch linux
 - Version 27

**Comment by dvallin** [comment]
The manual pipeline execution, did not pass filters to the planning steps. This has been fixed.
